anuga/file_conversion/dem2pts.py
anuga/shallow_water/shallow_water_domain.py
anuga/test_all.py

Simply exclude parallel directory from test_all search of unit test if pypar_available= False

Fixed issue #26

---

validation_tests/case_studies/merewether/runMerewether.py

Set sww output to smooth. Looks quite a bit better when saved smoothly. Also delete multiple sww file when running in parallel

delete multiple sww on completion

---

anuga/file_conversion/sww2dem.py
anuga/file_conversion/tests/test_sww2dem.py

Fixed issue #32 and also created a unit test to test case of sww2dem with verbose=True

Testing verbose mode of sww2dem fixing issue #32

---

anuga/abstract_2d_finite_volumes/quantity.py
anuga/file_conversion/dem2array.py
anuga/file_conversion/tests/test_dem2array.py
anuga/file_conversion/tests/test_file_conversion.py

Hello Steve,
I have fixed issue 43 by moving the Z = num.fliplr(Z.T) from quantity.py into dem2array.py/ Now Z array orientation between dem2array and grd2array is the same. I have also added a function: test_grd2array_dem2array in test_file_conversion.py to test the result between dem2array and grd2array arrays. They ended up the same.
Cheers
Hongji

Issue43 fix

---

anuga/operators/boundary_flux_integral_operator.py
anuga/operators/tests/test_boundary_flux_integral_operator.py

Extended the boundary_flux_integral_operator to work with DE2 algorithm.

Boundary flux issue#45

---

anuga/shallow_water/tests/test_shallow_water_domain.py

added function test_set_quantity_from_file in test_shallow_water_domain.py to test the results of set_quantity and set_values from pts, asc and dem files. The result of set_quantity and set_values should be the same.

added function test_set_quantity_from_file to test the results of set_quantity and set_values from pts, asc and dem files

---

anuga/abstract_2d_finite_volumes/generic_boundary_conditions.py
anuga/fit_interpolate/interpolate.py
anuga/shallow_water/boundaries.py
validation_tests/experimental_data/okushiri/run_okushiri.py

Small cleanup of the way file_function works with boundary conditions, especially when domain.time is outside of  the function domain of file_function.

File_function and boundary conditions

---

anuga/abstract_2d_finite_volumes/file_function.py
anuga/config.py

Set atol in numpy.allclose in file_function to be 1e-4. This seems to fix issue #66

Sts field boundary bug issue #66

---

anuga/abstract_2d_finite_volumes/quantity_ext.c

Small change to set_vertex_values in quantitiy_ext.c

Slight change of variable names

---

anuga/__init__.py
anuga/operators/sanddune_erosion_operator.py
examples/operators/run_sanddune_erosion.py

Adding in sanddune erosion operator created by Ted.

Parallel ted erosion

---

INSTALL.rst

This should be tested on another machine (besides just mine) before the Pull Request is merged. Thanks!

Added install instructions for Ubuntu on Windows 10

---

anuga/__init__.py
anuga/parallel/parallel_boyd_box_operator.py
anuga/parallel/parallel_boyd_pipe_operator.py
anuga/parallel/parallel_weir_orifice_trapezoid_operator.py
anuga/structures/boyd_box_operator.py
anuga/structures/boyd_pipe_operator.py
anuga/structures/internal_boundary_operator.py
anuga/structures/tests/test_weir_orifice_trapezoid_operator.py
anuga/structures/weir_orifice_trapezoid_operator.py

just adding in blockage and smoothing_timestep into the argument lists of weir_orifice_trapezoidal_operator

Weir orifice tests

---

anuga/parallel/parallel_boyd_box_operator.py
anuga/parallel/parallel_boyd_pipe_operator.py
anuga/parallel/parallel_operator_factory.py
anuga/parallel/parallel_structure_operator.py
anuga/structures/boyd_box_operator.py
anuga/structures/boyd_pipe_operator.py
anuga/structures/structure_operator.py
anuga/structures/tests/test_boyd_box_operator.py
anuga/structures/tests/test_boyd_pipe_operator.py

Hi Steve, i have added multiple barrels option to boyd pipe and box.
regards

added multiple barrels to boyd pipe and box

---

.travis.yml
anuga/fit_interpolate/setup.py
anuga/utilities/setup.py
tools/install_conda.sh
tools/install_conda_macos.sh

Added conda-forge Travis-CI build on linux and macos

Adding macos test

---

anuga/structures/boyd_box_operator.py
anuga/structures/boyd_pipe_operator.py
anuga/structures/tests/test_boyd_box_operator.py
examples/structures/run_culvert_inlet.py

Hi Steve, i have made some amendments to boyd culvert. There were issues with the code for multi barrels. Hopefully fixed now.
regards

amendments to boyd box and pipe

---

anuga/structures/boyd_pipe_operator.py

Hi Steve, i left verbose=True, now switched to False

minor amendment to boyd_pipe

---

anuga/abstract_2d_finite_volumes/quantity_ext.c

Change integer-size for all keys/indices, no changes to logic.

Changed quantity_ext module to use long integers (for large domains).

---

.travis.yml
anuga/setup.py
appveyor.yml
runtests.py
tools/install_conda_macos.sh

Making runtests work on windows

Win runtests

---

anuga/geospatial_data/tests/test_geospatial_data.py

added testcase where removal of leading spaces is allowed 

---

anuga/abstract_2d_finite_volumes/ermapper_grids.py
anuga/utilities/tests/test_plot_utils.py

Small change to suppress warning when using fromstring

frombuffer

---

anuga/abstract_2d_finite_volumes/tests/test_quantity.py
anuga/operators/rate_operators.py
anuga/operators/tests/test_rate_operators.py
anuga/pmesh/mesh_interface.py

timestepping_statistics was failing when using a quantity to set the rate in rate_operator.

timestepping_statistics now works with Q

---

validation_tests/case_studies/merewether/plot_results.py

Problem with latest version of numpy/matplotlib with "real"  index arrays and masked arrays.

Merewether plot results

---

anuga/file_conversion/file_conversion.py
anuga/file_conversion/tests/test_file_conversion.py
validation_tests/case_studies/merewether/plot_results.py
validation_tests/case_studies/merewether/results.tex

Exception not defined in try exception block

Bug timefile2netcdf

---

anuga/animate.py
anuga/shallow_water/shallow_water_domain.py
validation_tests/case_studies/towradgi_simulation/run_simulation.py
validation_tests/case_studies/towradgi_simulation/setup_boundaries.py

Simply copied over animate.py from the anuga clinic repository.

Clinic animate

---

anuga/config.py
anuga/shallow_water/shallow_water_domain.py
anuga/shallow_water/swDE1_domain_ext.c
anuga/shallow_water/sw_domain.h
anuga/shallow_water/tests/test_shallow_water_domain.py
anuga/shallow_water/tests/test_swb2_domain.py
anuga/shallow_water/tests/test_sww_interrogate.py
anuga/shallow_water/tests/test_system.py
validation_tests/analytical_exact/carrier_greenspan_periodic/numerical_carrier_greenspan.py
validation_tests/analytical_exact/carrier_greenspan_periodic/plot_results.py
validation_tests/analytical_exact/mac_donald_short_channel/numerical_MacDonald.py
validation_tests/analytical_exact/mac_donald_short_channel/plot_results.py
validation_tests/analytical_exact/mac_donald_short_channel/results.tex
validation_tests/analytical_exact/runup_on_sinusoid_beach/numerical_runup_sinusoid.py
validation_tests/analytical_exact/runup_on_sinusoid_beach/report.tex
validation_tests/analytical_exact/runup_on_sinusoid_beach/results.tex
validation_tests/analytical_exact/subcritical_flat/numerical_subcritical.py
validation_tests/analytical_exact/subcritical_flat/report.tex
validation_tests/analytical_exact/subcritical_flat/results.tex

Setup a low dispersion flux calculation for flows with very low froude number.
After setting up a domain and after any change of flow algorithm use 
domain.set_low_froude(1)
to use this new flux calculation.

Updated flux  for low Froude flows

---

anuga/parallel/parallel_api.py
anuga/parallel/sequential_distribute.py
anuga/parallel/tests/test_parallel_sw_flow_low_froude_0.py
anuga/parallel/tests/test_parallel_sw_flow_low_froude_1.py

Just an update to previous PR, so that low_froude variable is distributed correctly when distributing domains.

ensured that low_froude is broadcast in parallel

---

anuga/parallel/tests/test_parallel_sw_flow.py
anuga/parallel/tests/test_parallel_sw_flow_de0.py
anuga/parallel/tests/test_parallel_sw_flow_low_froude_0.py
anuga/parallel/tests/test_parallel_sw_flow_low_froude_1.py
anuga/parallel/tests/test_sequential_dist_sw_flow.py

Changed finaltime from 6 to 1 for the test_parallel_sw_flow tests.

Made some parallel test faster

---

.travis.yml
anuga/__init__.py
anuga/animate.py
anuga/utilities/animate.py

Adding animate wrappers as in the anuga clinic into the standard anuga source tree.

Added more to animate

---

.travis.yml
README.rst

remove coverage test

---

.travis.yml
anuga/utilities/animate.py

There was an error updating the depth when using the anuga animate display package used in jupyter notebooks.

Fixing animate for clinic notebooks

---

anuga/coordinate_transforms/redfearn.py
anuga/coordinate_transforms/tests/test_redfearn.py
anuga/pmesh/Pmw.py
anuga/pmesh/graphical_mesh_generator.py
appveyor.yml
tools/install_conda.sh
tools/install_conda_macos.sh
tools/install_ubuntu.sh

Updating some lat/lon code to deal with single points

lat-lon tests

---

README.rst

Advertise the python 3 development at anuga-community

advertise the python 3 version at anuga-community
